### ISSUE TITLE
Ditch Yaourt and Pacaur (Poll)

### ISSUE THREAD

**Issue by PizzaLovingNerd** [DYL-Communications/TermGet#3]
I'm thinking about getting rid of Yaourt support in favor of Pacaur support. This will be the last change before TermGet 2.0 comes out.

Comment the following to vote
1. Keep Yaourt
2. Use Pacaur

**Comment by SadError256** [comment]
Keep Yaourt

**Comment by tbilik** [comment]
I would probably say Pacaur, but most people don't have it, and they would have to install it through Yaourt ... Final vote though: Pacaur
